# -*- coding: utf-8 -*-
"""LIMPIAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqCYn3uzrdkth4ze80QWKC0pos-cIrBW
"""

import pandas as pd
import numpy as np

# 1. Cargamos el archivo
df = pd.read_csv('ventas_enormes_sucias.csv', encoding='utf-8')

# 2. Ver el tamaño inicial de la tabla
print(f"La tabla inició con: {df.shape[0]} filas.")
print("-" * 40)

# 3. Contar cuántas celdas vacías hay por columna
print("Datos vacíos por columna:")
print(df.isnull().sum())
print("-" * 40)

# 4. Contar cuántas filas están repetidas exactamente
print(f"Filas duplicadas: {df.duplicated().sum()}")

# Eliminamos duplicados y guardamos el resultado sobre el mismo 'df'
df = df.drop_duplicates()

print(f"Filas después de quitar duplicados: {df.shape[0]}")

# 1. Pasamos a minúscula y capitalizamos (lo que ya tenías)
df['Categoria'] = df['Categoria'].str.lower().str.capitalize()

# 2. UNIFICAMOS LA TILDE: Reemplazamos la versión incorrecta por la correcta
df['Categoria'] = df['Categoria'].replace('Electrodomesticos', 'Electrodomésticos')

# 3. Verificamos que ahora solo existan las categorías reales unificadas
print("📊 Categorías finales en la base de datos:")
print(df['Categoria'].unique())

# A. Borrar filas donde el Asesor sea nulo
df = df.dropna(subset=['Asesor'])

# B. Calcular el promedio de las ventas usando NumPy
promedio_ventas = df['Monto_Venta'].mean()
print(f"El promedio de ventas de la tienda es: ${promedio_ventas:,.2f} COP")

# C. Rellenar los vacíos del monto con ese promedio
df['Monto_Venta'] = df['Monto_Venta'].fillna(promedio_ventas)

print(f"Filas finales después de toda la limpieza: {df.shape[0]}")

df.to_csv('ventas_enormes_limpias.csv', index=False, encoding='utf-8-sig')
print("¡Felicidades! Tu archivo 'ventas_enormes_limpias.csv' ha sido exportado y está 100% limpio.")